name: Extend JSON

on:
  workflow_dispatch:
    inputs:
      url_to_json:
        description: 'URL to JSON file'
        default: 'https://raw.githubusercontent.com/DSACMS/repo-scaffolder/main/tier1/%7B%7Bcookiecutter.project_slug%7D%7D/repolinter.json'
        required: true
        type: string

jobs:
  extend-json:
    runs-on: ubuntu-latest
    name: Extend JSON file with extends property
    steps:
      - name: Extend JSON
        uses: ./.github/extendJSON
        with:
          url_to_json: ${{ github.event.inputs.url_to_json }