name: Extend JSON

on:
  workflow_dispatch:
    inputs:
      path_to_json:
        description: 'Path to JSON file'
        default: './repolinter.json'
        required: true
        type: string

jobs:
  extend-json:
    runs-on: ubuntu-latest
    name: Extend JSON file with extends property
    steps:
      - name: Extend JSON
        uses: ./.github/extendJSON
        with:
          path_to_json: 'tier4/{{cookiecutter.project_slug}}/repolinter.json'